name: floors_map_widget
description: "This widget allows you to create an interactive building map from
  an SVG image"
version: 0.0.1
homepage: https://github.com/ADC-Studio/floors_map_widget.git

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter: null
