name: floors_map_widget
description: "This widget allows you to create an interactive building map from
  an SVG image"
version: 1.0.0
homepage: https://github.com/ADC-Studio/floors_map_widget.git
repository: https://github.com/ADC-Studio/floors_map_widget.git
issue_tracker: https://github.com/ADC-Studio/floors_map_widget/issues
topics: ["map", "floor", "path builder", "building a route", "route", "svg", 
"architecture", "floor-navigation", "navigation", "interactive-map", "floor-plan", "widget"]

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  flutter_svg: ^2.0.10+1
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter: null
